### ISSUE TITLE
视频播放器电脑端没出现

### ISSUE THREAD

**Issue by machsix** [TransparentLC/dufs-material-assets#1]
版本信息:
1. dufs docker:
sigoden/dufs                           latest             d27156d6cd10   2 weeks ago     3.16MB

2. dufs-material-assets https://github.com/TransparentLC/dufs-material-assets/actions/runs/5329104873

尝试了最新的windows下的firefox(Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0)和edge(Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51)

显示分别如下
![image](https://github.com/TransparentLC/dufs-material-assets/assets/28209092/19115081-444a-444b-ab76-6284e035f350)

![image](https://github.com/TransparentLC/dufs-material-assets/assets/28209092/4d6e0f68-d4a3-4270-a739-79a2a5b82fc0)

主要表现为视频播放器缺失， 浏览器会直接打开。。手机上safari浏览器倒是一切正常

另外中间的框宽度貌似不会随着浏览器的缩放自动改变，长文件名的话要横向滚动

多谢作者辛苦开发！

**Comment by machsix** [comment]
研究了下发现可以改https://github.com/TransparentLC/dufs-material-assets/blob/770e3e45a034f1fc8dbf75d2c0e152277d73b08d/src/components/filelist.vue#L228

然而播放器不支持mkv。。

**Comment by TransparentLC** [comment]
这个视频播放用的是 HTML 原生的 `<video>` 标签，但是 mkv 并不是 HTML 标准支持的封装格式，所以对于 mkv 就没有添加播放视频的选项了。同理如果是 mp4 的视频但是视频编码用的是 HEVC，因为浏览器不支持 HEVC 解码，所以播放起来就会只有声音。

**Comment by TransparentLC** [comment]
![](https://github.com/TransparentLC/dufs-material-assets/assets/47057319/46e94a20-5e7f-4747-8bf8-f1630f4094d7)

因为你的截图里文件名特别长又不带空格所以浏览器默认就没有自动换行了，加了个 `overflow-wrap: anywhere` 应该能解决这个问题。
