### ISSUE TITLE
上传文件显示进度

### ISSUE THREAD

**Issue by shijianoo** [TransparentLC/dufs-material-assets#10]
上传大文件的时候，比如上传好几个G的文件，能不能加一个显示进度的功能。我记得默认的样式好像有这个功能

**Comment by TransparentLC** [comment]
原版前端用的 `XMLHttpRequest`，我这里用的是 `fetch`，但是 `fetch` 不支持处理上传进度，叹气（

https://github.com/TransparentLC/dufs-material-assets/blob/90c5af28def080f1ca05caced2e3c59dff94fa66/src/components/filelist.vue#L919-L931

还得在这里用 `XMLHttpRequest` 重新写一个……

**Comment by shijianoo** [comment]
加油，你可以的！

**Comment by TransparentLC** [comment]
![](https://github.com/user-attachments/assets/c846d15d-9440-4383-ad8a-30272ce8edd5)

大概会做成这样

**Comment by shijianoo** [comment]
非常好

**Comment by TransparentLC** [comment]
试一下最新的 commit？

**Comment by shijianoo** [comment]
不错，很好用
