### ISSUE TITLE
报错了/支持文本文件在线编辑

### ISSUE THREAD

**Issue by feipinxiang** [TransparentLC/dufs-material-assets#4]
dufs G:/Temp -p 80 -a admin:123@/:rw -A --assets D:\dufs\dufs-material-assets

Uncaught TypeError: Cannot read properties of undefined (reading 'dir_exists')
    at index.js:48:53
(anonymous) @ index.js:48

这一句const dirEmptyNote = PARAMS.q ? 'No results' : DATA.dir_exists ? 'Empty folder' : 'Folder will be created when a file is uploaded';

**Comment by feipinxiang** [comment]
GitHub Actions 下的有错误。nightly.link 里的没有

**Comment by TransparentLC** [comment]
不能复现，而且这个报错是 dufs 的原版的前端资源的代码。

https://github.com/sigoden/dufs/blob/75f06f749cb605fb607f157ed69573799d3c2db8/assets/index.js#L48

**Comment by feipinxiang** [comment]
> 不能复现，而且这个报错是 dufs 的原版的前端资源的代码。
> 
> https://github.com/sigoden/dufs/blob/75f06f749cb605fb607f157ed69573799d3c2db8/assets/index.js#L48

又试了下，应该是我运行原版后不清空浏览器缓存，然后--assets D:\dufs\dufs-material-assets会报错。清理了缓存没问题了。
有更新编辑txt/md文本的计划么？

**Comment by TransparentLC** [comment]
如果有需要的话我可以考虑加上，不过应该只考虑像记事本那样的纯文本编辑……

**Comment by feipinxiang** [comment]
> 如果有需要的话我可以考虑加上，不过应该只考虑像记事本那样的纯文本编辑……

感谢，有的话临时改个json什么的比较方便。是不是有代码高亮无所谓了。

**Comment by TransparentLC** [comment]
虽然引入带高亮的编辑器其实就可以，不过我觉得这又会让前端资源体积膨胀了，所以不太考虑。而且 dufs 加载前端资源的方式没办法做懒加载（比如只有点击编辑才会加载编辑器的部分）。

如果你尝试自己编译前端资源的话应该会能看到对资源大小的分析，代码高亮的部分已经占到了总大小的 50 KB（20%）。

**Comment by feipinxiang** [comment]
> 虽然引入带高亮的编辑器其实就可以，不过我觉得这又会让前端资源体积膨胀了，所以不太考虑。而且 dufs 加载前端资源的方式没办法做懒加载（比如只有点击编辑才会加载编辑器的部分）。
> 
> 如果你尝试自己编译前端资源的话应该会看到对资源大小的统计分析，只是那个代码高亮的功能就已经占到了总大小的 50 KB（20%）。

我主要是可能会临时改点json配置文件之类的，复杂修改的话就直接下载文件本地修改了。主要是网页上可以改文本的话那一些小修改可以省去一些下载保存打开修改再重新上传的步骤。虽然我在win下用对体积不在意，但我对高亮其实也没啥需求。
