### ISSUE TITLE
怎么没有拖拽文件或文件夹就自动上传的功能呢

### ISSUE THREAD

**Issue by shijianoo** [TransparentLC/dufs-material-assets#9]
怎么没有拖拽文件或文件夹就自动上传的功能呢

**Comment by shijianoo** [comment]
好像在放开鼠标左键的时候会报错
![screenshots](https://github.com/user-attachments/assets/833a8b89-0946-4101-b41a-729f2842337d)

**Comment by TransparentLC** [comment]
这功能本来是有的，这个是浏览器兼容问题……
